# Generated by Django 3.2.4 on 2021-06-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=250)),
                ('correct_answer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=250)),
                ('point', models.PositiveSmallIntegerField()),
                ('answers', models.ManyToManyField(to='quizzes.Answer')),
            ],
        ),
    ]
